# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselHolder',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_owl_carousel_carouselholder', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_owl_carousel_carouselitem', serialize=False, to='cms.CMSPlugin')),
                ('image_thumb', models.ImageField(null=True, upload_to='', verbose_name='Thumb image')),
                ('slide_index', models.IntegerField(default=1, verbose_name='slide_index')),
                ('caption', models.CharField(max_length=100, null=True)),
                ('text', models.TextField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Carousel Item',
                'verbose_name_plural': 'Carousel Items',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='OwlCarouselHolder',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_owl_carousel_owlcarouselholder', serialize=False, to='cms.CMSPlugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='OwlCarouselItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_owl_carousel_owlcarouselitem', serialize=False, to='cms.CMSPlugin')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Thumb image')),
                ('alt_text', models.CharField(max_length=100, null=True)),
                ('style', models.CharField(default='single-service-style-two', max_length=75, null=True)),
                ('icon', models.CharField(choices=[('industrio-icon-emails-interface-download-symbol', 'Download'), ('industrio-icon-pdf', 'PDF'), ('industrio-icon-menu', 'Menu'), ('industrio-icon-next', 'Next'), ('industrio-icon-coffee-cup', 'Coffee'), ('industrio-icon-team', 'Team'), ('industrio-icon-child', 'Child'), ('industrio-icon-play-button', 'Play'), ('industrio-icon-wind-engine', 'Wind engine'), ('industrio-icon-settings-1', 'Settings 1'), ('industrio-icon-delivery-truck', 'Truck'), ('industrio-icon-support', 'Support'), ('industrio-icon-secure-shield', 'Secure'), ('industrio-icon-atomic', 'Atomic'), ('industrio-icon-plant', 'Plant'), ('industrio-icon-settings', 'Settings'), ('industrio-icon-safety', 'Safety'), ('industrio-icon-drop-of-liquid', 'Drop'), ('industrio-icon-scythe', 'Scythe'), ('industrio-icon-factory-1', 'Factory-1'), ('industrio-icon-green-energy', 'Green energy'), ('industrio-icon-innovation', 'Innovation'), ('industrio-icon-gas-station-1', 'Gas station 1'), ('industrio-icon-layers', 'Layers'), ('industrio-icon-atom', 'Atom'), ('industrio-icon-flasks', 'Flasks'), ('industrio-icon-gas-station', 'Gas stations'), ('industrio-icon-gas-pipe', 'Gas pipe'), ('industrio-icon-tower', 'Tower'), ('industrio-icon-valve', 'Valve'), ('industrio-icon-industry', 'Industry'), ('industrio-icon-worker', 'Worker'), ('industrio-icon-envelope', 'Envelope'), ('industrio-icon-clock', 'Clock'), ('industrio-icon-phone-call', 'Phone call'), ('industrio-icon-right-quote', 'Right quote')], max_length=35)),
                ('title', models.CharField(max_length=75, null=True)),
                ('text', models.TextField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'OWL Carousel Item',
                'verbose_name_plural': 'OWL Carousel Items',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='OwlStyles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('main_template', models.FileField(upload_to='')),
                ('item_template', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='owlcarouselholder',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_owl_carousel.OwlStyles'),
        ),
    ]
