# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_owl_carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'verbose_name': 'Carousel Item', 'verbose_name_plural': 'Carousel Items'},
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='image_thumb',
            field=models.ImageField(null=True, upload_to='', verbose_name='Thumb image'),
        ),
    ]
