# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_owl_carousel', '0002_auto_20190303_1801'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carouselitem',
            table='djangocms_owl_carousel_carouselitem',
        ),
    ]
